# theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
title: Multimodal Fusion for Talking Face Generation Utilizing Speech-related Facial Action Units
description: The supplement materials of paper "Multimodal Fusion for Talking Face Generation Utilizing Speech-related Facial Action Units"
